name: gql_build
version: 0.0.11
description: Useful builders for your GraphQL SDL and documents. Based on package:gql_code_builder and package:build
repository: https://github.com/gql-dart/gql
environment:
  sdk: '>=2.7.2 <3.0.0'
dependencies:
  gql: ^0.12.1
  path: ^1.6.4
  glob: ^1.2.0
  build: ^1.0.0
  gql_code_builder: ^0.0.9
  code_builder: ^3.2.0
  dart_style: ^1.2.9
  built_value: ^7.1.0
  built_value_generator: ^7.1.0
  source_gen: ^0.9.5
  built_collection: ^4.3.2
dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.7
  gql_pedantic: ^1.0.1
dependency_overrides:
  code_builder:
    git:
      url: https://github.com/dart-lang/code_builder.git
      ref: a86c05e960f1e003e2158989c03117e1dd22858e
