name: end_to_end_test
version: 0.0.1
publish_to: none
description: Tests, not for publishing.\n
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.0.0-dev <3.0.0'
dependencies: 
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
  gql_build: ^0.0.11
  gql_code_builder: ^0.0.10
  gql_exec: ^0.2.4
dev_dependencies: 
  build: ^1.0.0
  build_runner: ^1.0.0
  test: ^1.0.0
